name: Testing code with Jest workflow
on:
 push:
   branches:
     - 'master'
     - 'main'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v3
        #https://github.com/actions/setup-node/blob/main/.github/workflows/versions.yml
        with:
          node-version-file: 'package.json'
          cache: npm
      - name: Install node dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./coverage/coverage-summary.json
          title: My Jest Coverage Comment
          summary-title: Test summary
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          junitxml-title: JUnit Title
          junitxml-path: ./coverage/junit.xml
          coverage-title: Coverage 
          coverage-path: ./coverage.txt

