name: Testing code with Jest workflow
on:
 push:
   branches:
     - 'master'
     - 'main'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v3
        #https://github.com/actions/setup-node/blob/main/.github/workflows/versions.yml
        with:
          node-version-file: 'package.json'
          cache: npm
      - name: Install node dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Archive coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: |
            ./coverage/coverage-summary.json
      - name: Jest Coverage Comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          hide-summary: true
          coverage-summary-path: ./coverage/coverage-summary.json
      - name: Check the output coverage
        run: |
          echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
          echo "Summary HTML - ${{ steps.coverageComment.outputs.summaryHtml }}"

      - name: Update README with Coverage HTML
        run: ${{ steps.coverageComment.outputs.summaryHtml }} >> tmp && mv -f tmp ./README.md 

      - name: Uyyyyyy
        run: cat ./README.md
      - name: Commit & Push changes in README
        uses: actions-js/push@master
        with:
          message: Update coverage in README
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
 # run: |
        #  sed -i "/<!-- Jest Coverage Comment:Begin -->/,/<!-- Jest Coverage Comment:End -->/c\<!-- Jest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.summaryHtml }}\n<!-- Jest Coverage Comment:End -->" ./README.md