name: Testing code with Jest workflow
on: workflow_dispatch

#on:
#  pull_request:
#    branches:
#      - 'master'
#      - 'main'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: npm
      - name: Install node dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Version check
        run: node --version
